import { Theme } from "../../models/Theme";

export const lightTheme: Theme = {
  colors: {
    primary: "#5222D0",
    secondary: "#040D1E",
    background: "#FFFFFF",
    backgroundMenu: "#F1F1F1",
    borderButtonHeader: "#E3E3E3",
    backgroundFooter: "#FFFFFF",
    gradient: "linear-gradient(to right, #ff00cc, #333399);",
    success: "#14C38E",
    error: "#d45d5d",
    text: "#1A1A1A",
    text_secondary: "#6F767E",
    input: "#F5F7F5",
    tableThead: "#f7f9fa",
    checkbox: "#040D1E",
    homeBackground: "#F8F8F8",
    underline: "#707070AD",
    backgroundContainer: "#FFFFFF",
    primaryTextTable: "#040D1E",
    stripe: "#eaeaea",
  },
  textSizes: {
    xg: "36px",
    g: "28px",
    "title-title-xl": "24px",
    "title-title-l": "20px",
    xm: "18px",
    "title-title-m": "16px",
    s: "14px",
    xs: "12px",
    "components-button-g": "22px",
    "components-button-m": "20px",
    "components-button-s": "16px",
  },
  fonts: {
    regular: "400",
    medium: "500",
    bold: "800",
    megaBold: "1200",
  },
};
